os: Visual Studio 2015

clone_folder: c:/projects/units

platform:
  - x64
  - x86

configuration:
  - Debug

environment:
  matrix:
    - GENERATOR: Visual Studio 14 2015 Win64
    - GENERATOR: Visual Studio 14 2015
    - GENERATOR: MinGW Makefiles

before_build:
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set PATH=C:\MinGW\bin;%PATH%
  - git submodule update --init --recursive
  - md build
  - cd build
  - cmake -Wno-dev -G"%GENERATOR%" ..

build_script:
  - cmake --build . --config %CONFIGURATION%

test_script:
  - cmd: ctest -VV -C %CONFIGURATION%

matrix:
  fast_finish: true
  allow_failures:
    - platform: x64
    - GENERATOR: Visual Studio 14 2015 Win32