version: 0.{build}.0
pull_requests:
  do_not_increment_build_number: true
configuration: Debug
platform: x64
clone_depth: 1
environment:
  matrix:
    - BUILD_SYSTEM: "Visual Studio 14 2015 Win64"
build_script:
- cmd: >-
    git submodule update --init --recursive

    mkdir build

    cd build

    cmake -G "%BUILD_SYSTEM%" ..

    cmake --build .
    
    ctest -V
