sudo: false
language: generic

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=g++ CXX=g++-6 CC=gcc-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libncurses5-dev

    - os: linux
      env: COMPILER_NAME=g++ CXX=g++-5 CC=gcc-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libncurses5-dev

    - os: linux
      env: COMPILER_NAME=clang++ CXX=clang++-3.9 CC=clang-3.9
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.9
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.9
            - libncurses5-dev

    - os: linux
      env: COMPILER_NAME=clang++ CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.8
            - libncurses5-dev

    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.7 CC=clang-3.7
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.7
            - libncurses5-dev

    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.6 CC=clang-3.6
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.6
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.6
            - libncurses5-dev
            
    - os: osx
      env: COMPILER=gcc CXX=g++ CC=gcc
    - os: osx
      env: COMPILER=clang CXX=clang++ CC=clang

before_script:
  - mkdir -p build
  - cd build

script:
  - export COVERALLS_SERVICE_NAME=travis-ci
  - export COVERALLS_REPO_TOKEN=xfGcbl2zMpSZ0KsOSSKcJ11XtDfTQKNQK
  - cmake -DCMAKE_BUILD_TYPE=Debug -DUNITS_BUILD_TESTS=ON -DUNITS_BUILD_DOCUMENTATION=OFF -DUNITS_ENABLE_COVERAGE=ON -DUNITS_ENABLE_COVERAGE_UPLOAD=ON ..
  - make
  - ctest
  - make coveralls

